### ISSUE TITLE
Issue from rock5/rock5b/other-os/android/low-level-dev

### ISSUE THREAD

**Issue by pixeltek-public** [radxa-docs/docs#143]
The Android build instructions for the repo init appear to be incorrect. The init URL appears to be not a public address.

See attempted repo init output below:

$ repo init -u git@192.168.2.13:rockchip_android_s/rk3588-manifests.git -b Android12_Radxa_rkr14 -m rockchip-s-local.xml
Downloading Repo source from https://gerrit.googlesource.com/git-repo

manifests:
ssh: connect to host 192.168.2.13 port 22: Connection timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
manifests: sleeping 4.0 seconds before retrying
fatal: cannot obtain manifest git@192.168.2.13:rockchip_android_s/rk3588-manifests.git
================================================================================
Repo command failed: UpdateManifestError
        Unable to sync manifest rockchip-s-local.xml

**Comment by akgnah** [comment]
fixed #153

**Comment by pixeltek-public** [comment]
Thank you for the fix. This has resolved the initial "repo init" failing issue, however there is a problem with the repo sync command. It is unable to download the "rk/libvendor_storage @ hardware/rockchip/libvendor_storage" repository and the sync command never completes.

**Comment by RadxaYuntian** [comment]
@y0w0 Please take a look above.

**Comment by pixeltek-public** [comment]
Just confirming that this now works correctly.
