### ISSUE TITLE
Issue from rock5/rock5a/accessories-guides/m.2-sata-break-board

### ISSUE THREAD

**Issue by Nishantdawn** [radxa-docs/docs#163]
I was following this link to setup SATA SSD on ROCK 5A board,

https://docs.radxa.com/en/rock5/rock5a/accessories-guides/m.2-sata-break-board

On the product page of this M2.E to SATA breakout board its showing that this is not supported on Rock5A board.

Please check this link:
https://www.okdo.com/us/p/m-2-e-key-to-sata-breakout-board-for-use-with-rock-single-board-computers/

**Comment by jack-ma** [comment]
Please refer our website for the compatibility: 

https://radxa.com/products/accessories/m2-ekey-to-sata-board

On the Okdo website, I did not see 5A is not supported for the M.2 E to SATA adapter.

**Comment by Nishantdawn** [comment]
They have comfimed over mail that this breakout board is supported and updated product page yesterday.
