### ISSUE TITLE
Issue from zero/zero2pro/low-level-dev/install-os-on-emmc

### ISSUE THREAD

**Issue by pitounet75** [radxa-docs/docs#204]
I tried to execute the procedure to flash [radxa-zero-erase-emmc.bin](https://dl.radxa.com/zero/images/loader/radxa-zero-erase-emmc.bin) on a radxa zero 2 Pro with 16GB of emmc, but it doesn't work. Once I clic on Run in RZ USB Boot Helper V1.0.0, it just write a few lines and doesn't flash anything.

![image](https://github.com/radxa-docs/docs/assets/58866691/2206e9a7-e003-4199-a1f2-7c95576b0e83)

![image](https://github.com/radxa-docs/docs/assets/58866691/36ffa58b-3c20-47ee-901a-43f04ed882ae)

**Comment by RadxaYuntian** [comment]
The download link is wrong. Please use https://dl.radxa.com/zero2pro/images/loader/radxa-zero-2pro-erase-emmc.bin for now.

**Comment by CodeChenL** [comment]
@pitounet75 fix by https://github.com/radxa-docs/docs/pull/277, can you close this issue?
