### ISSUE TITLE
Issue from rock5/rock5c/app-development/rknn_install

### ISSUE THREAD

**Issue by ranjitkathiriya** [radxa-docs/docs#345]
I am getting this errors trying below steps,

pip install packages/rknn_toolkit2-1.6.0+81f21f4d-cp39-cp39-linux_x86_64.whl 
Defaulting to user installation because normal site-packages is not writeable
ERROR: rknn_toolkit2-1.6.0+81f21f4d-cp39-cp39-linux_x86_64.whl is not a supported wheel on this platform.

and for this :

rock@rock-5c:~/Projects2/rknn-toolkit2/rknn-toolkit2$ pip install -r packages/requirements_cp38-1.6.0.txt -i https://mirror.baidu.com/pypi/simple
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://mirror.baidu.com/pypi/simple
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0xffff8a007610>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /pypi/simple/protobuf/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0xffff8a007940>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /pypi/simple/protobuf/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0xffff8a007af0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /pypi/simple/protobuf/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0xffff8a007ca0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /pypi/simple/protobuf/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0xffff8a007e50>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /pypi/simple/protobuf/
ERROR: Could not find a version that satisfies the requirement protobuf==3.20.3 (from versions: none)
ERROR: No matching distribution found for protobuf==3.20.3

**Comment by zifeng-radxa** [comment]
rknn_toolkit2 is for x86 platform, not for arm, so that you can not install in rock-5c,
on rock-5c you just need **rknn-toolkit2-lite**
