### ISSUE TITLE
5A ADC标注错误

### ISSUE THREAD

**Issue by RadxaYuntian** [radxa-docs/docs#4]
1. 中文GPIO电压表里面没有标明新版本所使用的ch2
2. 英文GPIO电压表里面没有标明老版本所使用的ch5
3. 英文GPIO电压表里面有没有任何版本使用过的ch4
4. ADC最大电压只到1.8V：
![image](https://github.com/radxa-docs/docs/assets/95260730/5c1c34ba-a66a-49ed-8890-f18020e98443)

**Comment by RadxaYuntian** [comment]
@peterwang2050 文档其他ADC应该也有同样的电压错误

**Comment by nascs** [comment]
> 1. 中文GPIO电压表里面没有标明新版本所使用的ch2
> 2. 英文GPIO电压表里面没有标明老版本所使用的ch5
> 3. 英文GPIO电压表里面有没有任何版本使用过的ch4
> 4. ADC最大电压只到1.8V：
>    ![image](https://private-user-images.githubusercontent.com/95260730/317115665-5c1c34ba-a66a-49ed-8890-f18020e98443.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NDU4MjksIm5iZiI6MTcxMzk0NTUyOSwicGF0aCI6Ii85NTI2MDczMC8zMTcxMTU2NjUtNWMxYzM0YmEtYTY2YS00OWVkLTg4OTAtZjE4MDIwZTk4NDQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDA3NTg0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5MzI1NmRmOTQ1MGI2OTRhNzY1ZjYxMDAwMmFkNjM3MGYxYzY0Nzk4OTVmOWQ5MjgxYWU1YWU0YzM5MDk0YjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HOxw7I88rfhaZwqZvmVAWdcnZqwSxZUV6tCgfe7Y_4I)

也就是文档要标明不同硬件版本中的使用过的 ADC？

**Comment by RadxaYuntian** [comment]
用户买了那自然文档要能查得到
文档提的issue一般都是客户提出来的支持问题
