### ISSUE TITLE
Debian没有sshd服务

### ISSUE THREAD

**Issue by RadxaYuntian** [radxa-docs/docs#402]
https://github.com/radxa-docs/documentation/commit/86bede99e1c783a9a6ef72e97348954bad7c58da#diff-542b004c1c875c67b62a105e9893a9547014fc885df56ebc4565fbb3ea82cb0aR16

**Comment by RadxaYuntian** [comment]
这个可能要再看看，debian 11上命令是可以的。也许是debian 12的问题
https://applink.feishu.cn/client/message/link/open?token=AmXlkMQNRgAcZrsHo9BMwAI%3D

**Comment by CodeChenL** [comment]
我在debian12测试，需要enable以后才有sshd
```prolog
rock@rock-5b:~$ sudo systemctl enable --now ssh
Synchronizing state of ssh.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable ssh
Created symlink /etc/systemd/system/sshd.service → /lib/systemd/system/ssh.service.
Created symlink /etc/systemd/system/multi-user.target.wants/ssh.service → /lib/systemd/system/ssh.service.
```

**Comment by RadxaYuntian** [comment]
都改成ssh，本来文档前面也都用的是ssh，不知道为啥这里又改了
