### ISSUE TITLE
RKNN Lite YOLOv8板端推理无需用户自行转换模型

### ISSUE THREAD

**Issue by RadxaYuntian** [radxa-docs/docs#50]
已在 rknn-model-zoo-rk* 包里面提供了转换后的模型：
https://github.com/radxa-docs/docs/blob/main/docs/common/dev/_rknn-toolkit-lite2-yolov8.mdx

**Comment by zifeng-radxa** [comment]
文档还需保留转模型的过程吗？

**Comment by RadxaYuntian** [comment]
"PC端模型转换"这一块既然写了也别删了，用户可能会自己训练模型，折叠一下放到文章末尾，告诉用户如果只是验证功能不需要自己转换。把“板端推理 YOLOv8”这里修改成使用自带的模型，然后提前。

**Comment by zifeng-radxa** [comment]
https://github.com/radxa-docs/docs/pull/136 为保证过程一致性，已添加 `yolov8.rknn 以提供` 提示，功能验证用户可直接跳转
